/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : string,
  'sensorType' : [] | [SensorType],
  'acknowledged' : boolean,
  'message' : string,
  'deviceId' : string,
  'timestamp' : Time,
  'severity' : { 'warning' : null } |
    { 'info' : null } |
    { 'critical' : null },
}
export interface AutomationRule {
  'id' : string,
  'createdBy' : string,
  'actions' : Array<
    {
      'command' : { 'turnOn' : null } |
        { 'turnOff' : null } |
        { 'setTemperature' : number },
      'deviceId' : string,
    }
  >,
  'lastModified' : Time,
  'enabled' : boolean,
  'conditions' : Array<BooleanRuleCondition>,
}
export interface BooleanRuleCondition {
  'comparison' : { 'notEqualTo' : null } |
    { 'equalTo' : null } |
    { 'greaterThan' : null } |
    { 'lessThan' : null },
  'sensorType' : SensorType,
  'threshold' : number,
  'deviceId' : string,
}
export interface Device {
  'id' : string,
  'status' : { 'maintenance' : null } |
    { 'offline' : null } |
    { 'online' : null },
  'lastReadingTimestamp' : Time,
  'deviceType' : DeviceType,
  'location' : { 'room' : string, 'building' : string },
}
export type DeviceType = { 'sensor' : SensorType } |
  { 'actuator' : { 'toggle' : null } | { 'thermostat' : null } };
export interface IoTUserProfile {
  'contactInfo' : string,
  'name' : string,
  'role' : [] | [UserRole],
  'department' : string,
}
export interface Recommendation {
  'id' : string,
  'estimatedImpact' : string,
  'description' : string,
  'timestamp' : Time,
  'category' : { 'operationalEfficiency' : null } |
    { 'energySavings' : null } |
    { 'spaceUtilization' : null },
}
export interface SensorReading {
  'sensorType' : SensorType,
  'value' : number,
  'unit' : string,
  'deviceId' : string,
  'timestamp' : Time,
}
export type SensorType = { 'occupancy' : null } |
  { 'temperature' : null } |
  { 'humidity' : null } |
  { 'energyConsumption' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlert' : ActorMethod<[Alert], undefined>,
  'createOrUpdateRule' : ActorMethod<[AutomationRule], undefined>,
  'deleteAlert' : ActorMethod<[string], undefined>,
  'deleteDevice' : ActorMethod<[string], undefined>,
  'deleteRecommendation' : ActorMethod<[string], undefined>,
  'deleteRule' : ActorMethod<[string], undefined>,
  'generateRecommendations' : ActorMethod<[], Array<Recommendation>>,
  'getAlert' : ActorMethod<[string], [] | [Alert]>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllDevices' : ActorMethod<[], Array<Device>>,
  'getAllRules' : ActorMethod<[], Array<AutomationRule>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [IoTUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDevice' : ActorMethod<[string], [] | [Device]>,
  'getLatestSensorReading' : ActorMethod<[string], [] | [SensorReading]>,
  'getRecommendations' : ActorMethod<[], Array<Recommendation>>,
  'getRule' : ActorMethod<[string], [] | [AutomationRule]>,
  'getSensorReadings' : ActorMethod<[string], Array<SensorReading>>,
  'getUnacknowledgedAlerts' : ActorMethod<[], Array<Alert>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [IoTUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSensorReading' : ActorMethod<[SensorReading], undefined>,
  'registerDevice' : ActorMethod<[Device], undefined>,
  'saveCallerUserProfile' : ActorMethod<[IoTUserProfile], undefined>,
  'toggleRule' : ActorMethod<[string, boolean], undefined>,
  'updateDeviceStatus' : ActorMethod<
    [
      string,
      { 'maintenance' : null } |
        { 'offline' : null } |
        { 'online' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];