/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SensorType = IDL.Variant({
  'occupancy' : IDL.Null,
  'temperature' : IDL.Null,
  'humidity' : IDL.Null,
  'energyConsumption' : IDL.Null,
});
export const Time = IDL.Int;
export const Alert = IDL.Record({
  'id' : IDL.Text,
  'sensorType' : IDL.Opt(SensorType),
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'deviceId' : IDL.Text,
  'timestamp' : Time,
  'severity' : IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  }),
});
export const BooleanRuleCondition = IDL.Record({
  'comparison' : IDL.Variant({
    'notEqualTo' : IDL.Null,
    'equalTo' : IDL.Null,
    'greaterThan' : IDL.Null,
    'lessThan' : IDL.Null,
  }),
  'sensorType' : SensorType,
  'threshold' : IDL.Float64,
  'deviceId' : IDL.Text,
});
export const AutomationRule = IDL.Record({
  'id' : IDL.Text,
  'createdBy' : IDL.Text,
  'actions' : IDL.Vec(
    IDL.Record({
      'command' : IDL.Variant({
        'turnOn' : IDL.Null,
        'turnOff' : IDL.Null,
        'setTemperature' : IDL.Float64,
      }),
      'deviceId' : IDL.Text,
    })
  ),
  'lastModified' : Time,
  'enabled' : IDL.Bool,
  'conditions' : IDL.Vec(BooleanRuleCondition),
});
export const Recommendation = IDL.Record({
  'id' : IDL.Text,
  'estimatedImpact' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Variant({
    'operationalEfficiency' : IDL.Null,
    'energySavings' : IDL.Null,
    'spaceUtilization' : IDL.Null,
  }),
});
export const DeviceType = IDL.Variant({
  'sensor' : SensorType,
  'actuator' : IDL.Variant({ 'toggle' : IDL.Null, 'thermostat' : IDL.Null }),
});
export const Device = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'maintenance' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  }),
  'lastReadingTimestamp' : Time,
  'deviceType' : DeviceType,
  'location' : IDL.Record({ 'room' : IDL.Text, 'building' : IDL.Text }),
});
export const IoTUserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Opt(UserRole),
  'department' : IDL.Text,
});
export const SensorReading = IDL.Record({
  'sensorType' : SensorType,
  'value' : IDL.Float64,
  'unit' : IDL.Text,
  'deviceId' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlert' : IDL.Func([Alert], [], []),
  'createOrUpdateRule' : IDL.Func([AutomationRule], [], []),
  'deleteAlert' : IDL.Func([IDL.Text], [], []),
  'deleteDevice' : IDL.Func([IDL.Text], [], []),
  'deleteRecommendation' : IDL.Func([IDL.Text], [], []),
  'deleteRule' : IDL.Func([IDL.Text], [], []),
  'generateRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], []),
  'getAlert' : IDL.Func([IDL.Text], [IDL.Opt(Alert)], ['query']),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
  'getAllRules' : IDL.Func([], [IDL.Vec(AutomationRule)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(IoTUserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevice' : IDL.Func([IDL.Text], [IDL.Opt(Device)], ['query']),
  'getLatestSensorReading' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SensorReading)],
      ['query'],
    ),
  'getRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], ['query']),
  'getRule' : IDL.Func([IDL.Text], [IDL.Opt(AutomationRule)], ['query']),
  'getSensorReadings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SensorReading)],
      ['query'],
    ),
  'getUnacknowledgedAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IoTUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSensorReading' : IDL.Func([SensorReading], [], []),
  'registerDevice' : IDL.Func([Device], [], []),
  'saveCallerUserProfile' : IDL.Func([IoTUserProfile], [], []),
  'toggleRule' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateDeviceStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'maintenance' : IDL.Null,
          'offline' : IDL.Null,
          'online' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SensorType = IDL.Variant({
    'occupancy' : IDL.Null,
    'temperature' : IDL.Null,
    'humidity' : IDL.Null,
    'energyConsumption' : IDL.Null,
  });
  const Time = IDL.Int;
  const Alert = IDL.Record({
    'id' : IDL.Text,
    'sensorType' : IDL.Opt(SensorType),
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'deviceId' : IDL.Text,
    'timestamp' : Time,
    'severity' : IDL.Variant({
      'warning' : IDL.Null,
      'info' : IDL.Null,
      'critical' : IDL.Null,
    }),
  });
  const BooleanRuleCondition = IDL.Record({
    'comparison' : IDL.Variant({
      'notEqualTo' : IDL.Null,
      'equalTo' : IDL.Null,
      'greaterThan' : IDL.Null,
      'lessThan' : IDL.Null,
    }),
    'sensorType' : SensorType,
    'threshold' : IDL.Float64,
    'deviceId' : IDL.Text,
  });
  const AutomationRule = IDL.Record({
    'id' : IDL.Text,
    'createdBy' : IDL.Text,
    'actions' : IDL.Vec(
      IDL.Record({
        'command' : IDL.Variant({
          'turnOn' : IDL.Null,
          'turnOff' : IDL.Null,
          'setTemperature' : IDL.Float64,
        }),
        'deviceId' : IDL.Text,
      })
    ),
    'lastModified' : Time,
    'enabled' : IDL.Bool,
    'conditions' : IDL.Vec(BooleanRuleCondition),
  });
  const Recommendation = IDL.Record({
    'id' : IDL.Text,
    'estimatedImpact' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Variant({
      'operationalEfficiency' : IDL.Null,
      'energySavings' : IDL.Null,
      'spaceUtilization' : IDL.Null,
    }),
  });
  const DeviceType = IDL.Variant({
    'sensor' : SensorType,
    'actuator' : IDL.Variant({ 'toggle' : IDL.Null, 'thermostat' : IDL.Null }),
  });
  const Device = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'maintenance' : IDL.Null,
      'offline' : IDL.Null,
      'online' : IDL.Null,
    }),
    'lastReadingTimestamp' : Time,
    'deviceType' : DeviceType,
    'location' : IDL.Record({ 'room' : IDL.Text, 'building' : IDL.Text }),
  });
  const IoTUserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Opt(UserRole),
    'department' : IDL.Text,
  });
  const SensorReading = IDL.Record({
    'sensorType' : SensorType,
    'value' : IDL.Float64,
    'unit' : IDL.Text,
    'deviceId' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlert' : IDL.Func([Alert], [], []),
    'createOrUpdateRule' : IDL.Func([AutomationRule], [], []),
    'deleteAlert' : IDL.Func([IDL.Text], [], []),
    'deleteDevice' : IDL.Func([IDL.Text], [], []),
    'deleteRecommendation' : IDL.Func([IDL.Text], [], []),
    'deleteRule' : IDL.Func([IDL.Text], [], []),
    'generateRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], []),
    'getAlert' : IDL.Func([IDL.Text], [IDL.Opt(Alert)], ['query']),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
    'getAllRules' : IDL.Func([], [IDL.Vec(AutomationRule)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(IoTUserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevice' : IDL.Func([IDL.Text], [IDL.Opt(Device)], ['query']),
    'getLatestSensorReading' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SensorReading)],
        ['query'],
      ),
    'getRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], ['query']),
    'getRule' : IDL.Func([IDL.Text], [IDL.Opt(AutomationRule)], ['query']),
    'getSensorReadings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SensorReading)],
        ['query'],
      ),
    'getUnacknowledgedAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IoTUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSensorReading' : IDL.Func([SensorReading], [], []),
    'registerDevice' : IDL.Func([Device], [], []),
    'saveCallerUserProfile' : IDL.Func([IoTUserProfile], [], []),
    'toggleRule' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateDeviceStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'maintenance' : IDL.Null,
            'offline' : IDL.Null,
            'online' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };