/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IoTUserProfile {
    contactInfo: string;
    name: string;
    role?: UserRole;
    department: string;
}
export type Time = bigint;
export interface AutomationRule {
    id: string;
    createdBy: string;
    actions: Array<{
        command: {
            __kind__: "turnOn";
            turnOn: null;
        } | {
            __kind__: "turnOff";
            turnOff: null;
        } | {
            __kind__: "setTemperature";
            setTemperature: number;
        };
        deviceId: string;
    }>;
    lastModified: Time;
    enabled: boolean;
    conditions: Array<BooleanRuleCondition>;
}
export interface SensorReading {
    sensorType: SensorType;
    value: number;
    unit: string;
    deviceId: string;
    timestamp: Time;
}
export interface Recommendation {
    id: string;
    estimatedImpact: string;
    description: string;
    timestamp: Time;
    category: Variant_operationalEfficiency_energySavings_spaceUtilization;
}
export type DeviceType = {
    __kind__: "sensor";
    sensor: SensorType;
} | {
    __kind__: "actuator";
    actuator: Variant_toggle_thermostat;
};
export interface BooleanRuleCondition {
    comparison: Variant_notEqualTo_equalTo_greaterThan_lessThan;
    sensorType: SensorType;
    threshold: number;
    deviceId: string;
}
export interface Alert {
    id: string;
    sensorType?: SensorType;
    acknowledged: boolean;
    message: string;
    deviceId: string;
    timestamp: Time;
    severity: Variant_warning_info_critical;
}
export interface Device {
    id: string;
    status: Variant_maintenance_offline_online;
    lastReadingTimestamp: Time;
    deviceType: DeviceType;
    location: {
        room: string;
        building: string;
    };
}
export enum SensorType {
    occupancy = "occupancy",
    temperature = "temperature",
    humidity = "humidity",
    energyConsumption = "energyConsumption"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_maintenance_offline_online {
    maintenance = "maintenance",
    offline = "offline",
    online = "online"
}
export enum Variant_notEqualTo_equalTo_greaterThan_lessThan {
    notEqualTo = "notEqualTo",
    equalTo = "equalTo",
    greaterThan = "greaterThan",
    lessThan = "lessThan"
}
export enum Variant_operationalEfficiency_energySavings_spaceUtilization {
    operationalEfficiency = "operationalEfficiency",
    energySavings = "energySavings",
    spaceUtilization = "spaceUtilization"
}
export enum Variant_toggle_thermostat {
    toggle = "toggle",
    thermostat = "thermostat"
}
export enum Variant_warning_info_critical {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeAlert(alertId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlert(alert: Alert): Promise<void>;
    createOrUpdateRule(rule: AutomationRule): Promise<void>;
    deleteAlert(alertId: string): Promise<void>;
    deleteDevice(deviceId: string): Promise<void>;
    deleteRecommendation(recId: string): Promise<void>;
    deleteRule(ruleId: string): Promise<void>;
    generateRecommendations(): Promise<Array<Recommendation>>;
    getAlert(alertId: string): Promise<Alert | null>;
    getAllAlerts(): Promise<Array<Alert>>;
    getAllDevices(): Promise<Array<Device>>;
    getAllRules(): Promise<Array<AutomationRule>>;
    getCallerUserProfile(): Promise<IoTUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDevice(id: string): Promise<Device | null>;
    getLatestSensorReading(deviceId: string): Promise<SensorReading | null>;
    getRecommendations(): Promise<Array<Recommendation>>;
    getRule(id: string): Promise<AutomationRule | null>;
    getSensorReadings(deviceId: string): Promise<Array<SensorReading>>;
    getUnacknowledgedAlerts(): Promise<Array<Alert>>;
    getUserProfile(user: Principal): Promise<IoTUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordSensorReading(reading: SensorReading): Promise<void>;
    registerDevice(device: Device): Promise<void>;
    saveCallerUserProfile(profile: IoTUserProfile): Promise<void>;
    toggleRule(ruleId: string, enabled: boolean): Promise<void>;
    updateDeviceStatus(deviceId: string, status: Variant_maintenance_offline_online): Promise<void>;
}
import type { Alert as _Alert, AutomationRule as _AutomationRule, BooleanRuleCondition as _BooleanRuleCondition, Device as _Device, DeviceType as _DeviceType, IoTUserProfile as _IoTUserProfile, Recommendation as _Recommendation, SensorReading as _SensorReading, SensorType as _SensorType, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlert(arg0: Alert): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(to_candid_Alert_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(to_candid_Alert_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateRule(arg0: AutomationRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateRule(to_candid_AutomationRule_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateRule(to_candid_AutomationRule_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0);
            return result;
        }
    }
    async deleteDevice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDevice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDevice(arg0);
            return result;
        }
    }
    async deleteRecommendation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecommendation(arg0);
            return result;
        }
    }
    async deleteRule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRule(arg0);
            return result;
        }
    }
    async generateRecommendations(): Promise<Array<Recommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateRecommendations();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateRecommendations();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlert(arg0: string): Promise<Alert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlert(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlert(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDevices(): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRules(): Promise<Array<AutomationRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRules();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRules();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<IoTUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevice(arg0: string): Promise<Device | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevice(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevice(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestSensorReading(arg0: string): Promise<SensorReading | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestSensorReading(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestSensorReading(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(): Promise<Array<Recommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRule(arg0: string): Promise<AutomationRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRule(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRule(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensorReadings(arg0: string): Promise<Array<SensorReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensorReadings(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensorReadings(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnacknowledgedAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnacknowledgedAlerts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnacknowledgedAlerts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<IoTUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordSensorReading(arg0: SensorReading): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSensorReading(to_candid_SensorReading_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSensorReading(to_candid_SensorReading_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerDevice(arg0: Device): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(to_candid_Device_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(to_candid_Device_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: IoTUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_IoTUserProfile_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_IoTUserProfile_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleRule(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleRule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleRule(arg0, arg1);
            return result;
        }
    }
    async updateDeviceStatus(arg0: string, arg1: Variant_maintenance_offline_online): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeviceStatus(arg0, to_candid_variant_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeviceStatus(arg0, to_candid_variant_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Alert_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_AutomationRule_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutomationRule): AutomationRule {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_BooleanRuleCondition_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BooleanRuleCondition): BooleanRuleCondition {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_DeviceType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceType): DeviceType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Device_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Device): Device {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_IoTUserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IoTUserProfile): IoTUserProfile {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SensorReading_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SensorReading): SensorReading {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_SensorType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SensorType): SensorType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Alert]): Alert | null {
    return value.length === 0 ? null : from_candid_Alert_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SensorType]): SensorType | null {
    return value.length === 0 ? null : from_candid_SensorType_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IoTUserProfile]): IoTUserProfile | null {
    return value.length === 0 ? null : from_candid_IoTUserProfile_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Device]): Device | null {
    return value.length === 0 ? null : from_candid_Device_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SensorReading]): SensorReading | null {
    return value.length === 0 ? null : from_candid_SensorReading_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AutomationRule]): AutomationRule | null {
    return value.length === 0 ? null : from_candid_AutomationRule_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    estimatedImpact: string;
    description: string;
    timestamp: _Time;
    category: {
        operationalEfficiency: null;
    } | {
        energySavings: null;
    } | {
        spaceUtilization: null;
    };
}): {
    id: string;
    estimatedImpact: string;
    description: string;
    timestamp: Time;
    category: Variant_operationalEfficiency_energySavings_spaceUtilization;
} {
    return {
        id: value.id,
        estimatedImpact: value.estimatedImpact,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_variant_n20(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sensorType: [] | [_SensorType];
    acknowledged: boolean;
    message: string;
    deviceId: string;
    timestamp: _Time;
    severity: {
        warning: null;
    } | {
        info: null;
    } | {
        critical: null;
    };
}): {
    id: string;
    sensorType?: SensorType;
    acknowledged: boolean;
    message: string;
    deviceId: string;
    timestamp: Time;
    severity: Variant_warning_info_critical;
} {
    return {
        id: value.id,
        sensorType: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.sensorType)),
        acknowledged: value.acknowledged,
        message: value.message,
        deviceId: value.deviceId,
        timestamp: value.timestamp,
        severity: from_candid_variant_n27(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        maintenance: null;
    } | {
        offline: null;
    } | {
        online: null;
    };
    lastReadingTimestamp: _Time;
    deviceType: _DeviceType;
    location: {
        room: string;
        building: string;
    };
}): {
    id: string;
    status: Variant_maintenance_offline_online;
    lastReadingTimestamp: Time;
    deviceType: DeviceType;
    location: {
        room: string;
        building: string;
    };
} {
    return {
        id: value.id,
        status: from_candid_variant_n32(_uploadFile, _downloadFile, value.status),
        lastReadingTimestamp: value.lastReadingTimestamp,
        deviceType: from_candid_DeviceType_n33(_uploadFile, _downloadFile, value.deviceType),
        location: value.location
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdBy: string;
    actions: Array<{
        command: {
            turnOn: null;
        } | {
            turnOff: null;
        } | {
            setTemperature: number;
        };
        deviceId: string;
    }>;
    lastModified: _Time;
    enabled: boolean;
    conditions: Array<_BooleanRuleCondition>;
}): {
    id: string;
    createdBy: string;
    actions: Array<{
        command: {
            __kind__: "turnOn";
            turnOn: null;
        } | {
            __kind__: "turnOff";
            turnOff: null;
        } | {
            __kind__: "setTemperature";
            setTemperature: number;
        };
        deviceId: string;
    }>;
    lastModified: Time;
    enabled: boolean;
    conditions: Array<BooleanRuleCondition>;
} {
    return {
        id: value.id,
        createdBy: value.createdBy,
        actions: from_candid_vec_n39(_uploadFile, _downloadFile, value.actions),
        lastModified: value.lastModified,
        enabled: value.enabled,
        conditions: from_candid_vec_n42(_uploadFile, _downloadFile, value.conditions)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    command: {
        turnOn: null;
    } | {
        turnOff: null;
    } | {
        setTemperature: number;
    };
    deviceId: string;
}): {
    command: {
        __kind__: "turnOn";
        turnOn: null;
    } | {
        __kind__: "turnOff";
        turnOff: null;
    } | {
        __kind__: "setTemperature";
        setTemperature: number;
    };
    deviceId: string;
} {
    return {
        command: from_candid_variant_n41(_uploadFile, _downloadFile, value.command),
        deviceId: value.deviceId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    comparison: {
        notEqualTo: null;
    } | {
        equalTo: null;
    } | {
        greaterThan: null;
    } | {
        lessThan: null;
    };
    sensorType: _SensorType;
    threshold: number;
    deviceId: string;
}): {
    comparison: Variant_notEqualTo_equalTo_greaterThan_lessThan;
    sensorType: SensorType;
    threshold: number;
    deviceId: string;
} {
    return {
        comparison: from_candid_variant_n45(_uploadFile, _downloadFile, value.comparison),
        sensorType: from_candid_SensorType_n25(_uploadFile, _downloadFile, value.sensorType),
        threshold: value.threshold,
        deviceId: value.deviceId
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    role: [] | [_UserRole];
    department: string;
}): {
    contactInfo: string;
    name: string;
    role?: UserRole;
    department: string;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.role)),
        department: value.department
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sensorType: _SensorType;
    value: number;
    unit: string;
    deviceId: string;
    timestamp: _Time;
}): {
    sensorType: SensorType;
    value: number;
    unit: string;
    deviceId: string;
    timestamp: Time;
} {
    return {
        sensorType: from_candid_SensorType_n25(_uploadFile, _downloadFile, value.sensorType),
        value: value.value,
        unit: value.unit,
        deviceId: value.deviceId,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    operationalEfficiency: null;
} | {
    energySavings: null;
} | {
    spaceUtilization: null;
}): Variant_operationalEfficiency_energySavings_spaceUtilization {
    return "operationalEfficiency" in value ? Variant_operationalEfficiency_energySavings_spaceUtilization.operationalEfficiency : "energySavings" in value ? Variant_operationalEfficiency_energySavings_spaceUtilization.energySavings : "spaceUtilization" in value ? Variant_operationalEfficiency_energySavings_spaceUtilization.spaceUtilization : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupancy: null;
} | {
    temperature: null;
} | {
    humidity: null;
} | {
    energyConsumption: null;
}): SensorType {
    return "occupancy" in value ? SensorType.occupancy : "temperature" in value ? SensorType.temperature : "humidity" in value ? SensorType.humidity : "energyConsumption" in value ? SensorType.energyConsumption : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): Variant_warning_info_critical {
    return "warning" in value ? Variant_warning_info_critical.warning : "info" in value ? Variant_warning_info_critical.info : "critical" in value ? Variant_warning_info_critical.critical : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maintenance: null;
} | {
    offline: null;
} | {
    online: null;
}): Variant_maintenance_offline_online {
    return "maintenance" in value ? Variant_maintenance_offline_online.maintenance : "offline" in value ? Variant_maintenance_offline_online.offline : "online" in value ? Variant_maintenance_offline_online.online : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sensor: _SensorType;
} | {
    actuator: {
        toggle: null;
    } | {
        thermostat: null;
    };
}): {
    __kind__: "sensor";
    sensor: SensorType;
} | {
    __kind__: "actuator";
    actuator: Variant_toggle_thermostat;
} {
    return "sensor" in value ? {
        __kind__: "sensor",
        sensor: from_candid_SensorType_n25(_uploadFile, _downloadFile, value.sensor)
    } : "actuator" in value ? {
        __kind__: "actuator",
        actuator: from_candid_variant_n35(_uploadFile, _downloadFile, value.actuator)
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toggle: null;
} | {
    thermostat: null;
}): Variant_toggle_thermostat {
    return "toggle" in value ? Variant_toggle_thermostat.toggle : "thermostat" in value ? Variant_toggle_thermostat.thermostat : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    turnOn: null;
} | {
    turnOff: null;
} | {
    setTemperature: number;
}): {
    __kind__: "turnOn";
    turnOn: null;
} | {
    __kind__: "turnOff";
    turnOff: null;
} | {
    __kind__: "setTemperature";
    setTemperature: number;
} {
    return "turnOn" in value ? {
        __kind__: "turnOn",
        turnOn: value.turnOn
    } : "turnOff" in value ? {
        __kind__: "turnOff",
        turnOff: value.turnOff
    } : "setTemperature" in value ? {
        __kind__: "setTemperature",
        setTemperature: value.setTemperature
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notEqualTo: null;
} | {
    equalTo: null;
} | {
    greaterThan: null;
} | {
    lessThan: null;
}): Variant_notEqualTo_equalTo_greaterThan_lessThan {
    return "notEqualTo" in value ? Variant_notEqualTo_equalTo_greaterThan_lessThan.notEqualTo : "equalTo" in value ? Variant_notEqualTo_equalTo_greaterThan_lessThan.equalTo : "greaterThan" in value ? Variant_notEqualTo_equalTo_greaterThan_lessThan.greaterThan : "lessThan" in value ? Variant_notEqualTo_equalTo_greaterThan_lessThan.lessThan : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recommendation>): Array<Recommendation> {
    return value.map((x)=>from_candid_Recommendation_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Device>): Array<Device> {
    return value.map((x)=>from_candid_Device_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AutomationRule>): Array<AutomationRule> {
    return value.map((x)=>from_candid_AutomationRule_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    command: {
        turnOn: null;
    } | {
        turnOff: null;
    } | {
        setTemperature: number;
    };
    deviceId: string;
}>): Array<{
    command: {
        __kind__: "turnOn";
        turnOn: null;
    } | {
        __kind__: "turnOff";
        turnOff: null;
    } | {
        __kind__: "setTemperature";
        setTemperature: number;
    };
    deviceId: string;
}> {
    return value.map((x)=>from_candid_record_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BooleanRuleCondition>): Array<BooleanRuleCondition> {
    return value.map((x)=>from_candid_BooleanRuleCondition_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SensorReading>): Array<SensorReading> {
    return value.map((x)=>from_candid_SensorReading_n54(_uploadFile, _downloadFile, x));
}
function to_candid_Alert_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alert): _Alert {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AutomationRule_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AutomationRule): _AutomationRule {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BooleanRuleCondition_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BooleanRuleCondition): _BooleanRuleCondition {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DeviceType_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceType): _DeviceType {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_Device_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Device): _Device {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_IoTUserProfile_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IoTUserProfile): _IoTUserProfile {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_SensorReading_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorReading): _SensorReading {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_SensorType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorType): _SensorType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    command: {
        __kind__: "turnOn";
        turnOn: null;
    } | {
        __kind__: "turnOff";
        turnOff: null;
    } | {
        __kind__: "setTemperature";
        setTemperature: number;
    };
    deviceId: string;
}): {
    command: {
        turnOn: null;
    } | {
        turnOff: null;
    } | {
        setTemperature: number;
    };
    deviceId: string;
} {
    return {
        command: to_candid_variant_n12(_uploadFile, _downloadFile, value.command),
        deviceId: value.deviceId
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    comparison: Variant_notEqualTo_equalTo_greaterThan_lessThan;
    sensorType: SensorType;
    threshold: number;
    deviceId: string;
}): {
    comparison: {
        notEqualTo: null;
    } | {
        equalTo: null;
    } | {
        greaterThan: null;
    } | {
        lessThan: null;
    };
    sensorType: _SensorType;
    threshold: number;
    deviceId: string;
} {
    return {
        comparison: to_candid_variant_n16(_uploadFile, _downloadFile, value.comparison),
        sensorType: to_candid_SensorType_n5(_uploadFile, _downloadFile, value.sensorType),
        threshold: value.threshold,
        deviceId: value.deviceId
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sensorType?: SensorType;
    acknowledged: boolean;
    message: string;
    deviceId: string;
    timestamp: Time;
    severity: Variant_warning_info_critical;
}): {
    id: string;
    sensorType: [] | [_SensorType];
    acknowledged: boolean;
    message: string;
    deviceId: string;
    timestamp: _Time;
    severity: {
        warning: null;
    } | {
        info: null;
    } | {
        critical: null;
    };
} {
    return {
        id: value.id,
        sensorType: value.sensorType ? candid_some(to_candid_SensorType_n5(_uploadFile, _downloadFile, value.sensorType)) : candid_none(),
        acknowledged: value.acknowledged,
        message: value.message,
        deviceId: value.deviceId,
        timestamp: value.timestamp,
        severity: to_candid_variant_n7(_uploadFile, _downloadFile, value.severity)
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sensorType: SensorType;
    value: number;
    unit: string;
    deviceId: string;
    timestamp: Time;
}): {
    sensorType: _SensorType;
    value: number;
    unit: string;
    deviceId: string;
    timestamp: _Time;
} {
    return {
        sensorType: to_candid_SensorType_n5(_uploadFile, _downloadFile, value.sensorType),
        value: value.value,
        unit: value.unit,
        deviceId: value.deviceId,
        timestamp: value.timestamp
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_maintenance_offline_online;
    lastReadingTimestamp: Time;
    deviceType: DeviceType;
    location: {
        room: string;
        building: string;
    };
}): {
    id: string;
    status: {
        maintenance: null;
    } | {
        offline: null;
    } | {
        online: null;
    };
    lastReadingTimestamp: _Time;
    deviceType: _DeviceType;
    location: {
        room: string;
        building: string;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n62(_uploadFile, _downloadFile, value.status),
        lastReadingTimestamp: value.lastReadingTimestamp,
        deviceType: to_candid_DeviceType_n63(_uploadFile, _downloadFile, value.deviceType),
        location: value.location
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    role?: UserRole;
    department: string;
}): {
    contactInfo: string;
    name: string;
    role: [] | [_UserRole];
    department: string;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        role: value.role ? candid_some(to_candid_UserRole_n1(_uploadFile, _downloadFile, value.role)) : candid_none(),
        department: value.department
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdBy: string;
    actions: Array<{
        command: {
            __kind__: "turnOn";
            turnOn: null;
        } | {
            __kind__: "turnOff";
            turnOff: null;
        } | {
            __kind__: "setTemperature";
            setTemperature: number;
        };
        deviceId: string;
    }>;
    lastModified: Time;
    enabled: boolean;
    conditions: Array<BooleanRuleCondition>;
}): {
    id: string;
    createdBy: string;
    actions: Array<{
        command: {
            turnOn: null;
        } | {
            turnOff: null;
        } | {
            setTemperature: number;
        };
        deviceId: string;
    }>;
    lastModified: _Time;
    enabled: boolean;
    conditions: Array<_BooleanRuleCondition>;
} {
    return {
        id: value.id,
        createdBy: value.createdBy,
        actions: to_candid_vec_n10(_uploadFile, _downloadFile, value.actions),
        lastModified: value.lastModified,
        enabled: value.enabled,
        conditions: to_candid_vec_n13(_uploadFile, _downloadFile, value.conditions)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "turnOn";
    turnOn: null;
} | {
    __kind__: "turnOff";
    turnOff: null;
} | {
    __kind__: "setTemperature";
    setTemperature: number;
}): {
    turnOn: null;
} | {
    turnOff: null;
} | {
    setTemperature: number;
} {
    return value.__kind__ === "turnOn" ? {
        turnOn: value.turnOn
    } : value.__kind__ === "turnOff" ? {
        turnOff: value.turnOff
    } : value.__kind__ === "setTemperature" ? {
        setTemperature: value.setTemperature
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_notEqualTo_equalTo_greaterThan_lessThan): {
    notEqualTo: null;
} | {
    equalTo: null;
} | {
    greaterThan: null;
} | {
    lessThan: null;
} {
    return value == Variant_notEqualTo_equalTo_greaterThan_lessThan.notEqualTo ? {
        notEqualTo: null
    } : value == Variant_notEqualTo_equalTo_greaterThan_lessThan.equalTo ? {
        equalTo: null
    } : value == Variant_notEqualTo_equalTo_greaterThan_lessThan.greaterThan ? {
        greaterThan: null
    } : value == Variant_notEqualTo_equalTo_greaterThan_lessThan.lessThan ? {
        lessThan: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SensorType): {
    occupancy: null;
} | {
    temperature: null;
} | {
    humidity: null;
} | {
    energyConsumption: null;
} {
    return value == SensorType.occupancy ? {
        occupancy: null
    } : value == SensorType.temperature ? {
        temperature: null
    } : value == SensorType.humidity ? {
        humidity: null
    } : value == SensorType.energyConsumption ? {
        energyConsumption: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_maintenance_offline_online): {
    maintenance: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == Variant_maintenance_offline_online.maintenance ? {
        maintenance: null
    } : value == Variant_maintenance_offline_online.offline ? {
        offline: null
    } : value == Variant_maintenance_offline_online.online ? {
        online: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "sensor";
    sensor: SensorType;
} | {
    __kind__: "actuator";
    actuator: Variant_toggle_thermostat;
}): {
    sensor: _SensorType;
} | {
    actuator: {
        toggle: null;
    } | {
        thermostat: null;
    };
} {
    return value.__kind__ === "sensor" ? {
        sensor: to_candid_SensorType_n5(_uploadFile, _downloadFile, value.sensor)
    } : value.__kind__ === "actuator" ? {
        actuator: to_candid_variant_n65(_uploadFile, _downloadFile, value.actuator)
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_toggle_thermostat): {
    toggle: null;
} | {
    thermostat: null;
} {
    return value == Variant_toggle_thermostat.toggle ? {
        toggle: null
    } : value == Variant_toggle_thermostat.thermostat ? {
        thermostat: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_warning_info_critical): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == Variant_warning_info_critical.warning ? {
        warning: null
    } : value == Variant_warning_info_critical.info ? {
        info: null
    } : value == Variant_warning_info_critical.critical ? {
        critical: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    command: {
        __kind__: "turnOn";
        turnOn: null;
    } | {
        __kind__: "turnOff";
        turnOff: null;
    } | {
        __kind__: "setTemperature";
        setTemperature: number;
    };
    deviceId: string;
}>): Array<{
    command: {
        turnOn: null;
    } | {
        turnOff: null;
    } | {
        setTemperature: number;
    };
    deviceId: string;
}> {
    return value.map((x)=>to_candid_record_n11(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BooleanRuleCondition>): Array<_BooleanRuleCondition> {
    return value.map((x)=>to_candid_BooleanRuleCondition_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
